version: 0.0
os: linux
files:
  - source: /
    destination: /opt/weather-forecast-app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: root