# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building images - $(date)"

      # 1. Rails image – uses your existing Dockerfile in the root
      - echo "Building Rails image..."
      - docker build -t weatherforecast-rails:latest ./rails_backend
      - docker tag weatherforecast-rails:latest 414708969810.dkr.ecr.us-east-2.amazonaws.com/weatherforecast-rails:latest

      # 2. React image – exact same dev server you run on EC2 today
      - echo "Creating temporary Dockerfile for React dev server..."
      - |
        cat > Dockerfile.react <<'EOF'
        FROM node:16-alpine

        WORKDIR /app

        RUN apk add --no-cache netcat-openbsd

        COPY package*.json ./
        RUN npm ci --legacy-peer-deps

        COPY . .

        ENV HOST=0.0.0.0 \
            PORT=3000 \
            CHOKIDAR_USEPOLLING=true \
            HOME=/tmp

        EXPOSE 3000

        CMD sh -c "until nc -z rails 3001; do echo 'Waiting for Rails...'; sleep 3; done && npm run start-docker"
        EOF

      - echo "Building React development server image..."
      - docker build -t weatherforecast-react:latest ./react_frontend
      - docker tag weatherforecast-react:latest 414708969810.dkr.ecr.us-east-2.amazonaws.com/weatherforecast-react:latest

      - rm -f Dockerfile.react   # clean up

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push 414708969810.dkr.ecr.us-east-2.amazonaws.com/weatherforecast-rails:latest
      - docker push 414708969810.dkr.ecr.us-east-2.amazonaws.com/weatherforecast-react:latest

      - printf '[{"name":"rails","imageUri":"414708969810.dkr.ecr.us-east-2.amazonaws.com/weatherforecast-rails:latest"},{"name":"react","imageUri":"414708969810.dkr.ecr.us-east-2.amazonaws.com/weatherforecast-react:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      - echo "Build completed - $(date)"

artifacts:
  files:
    - imagedefinitions.json
    - docker-compose.yml
    - appspec.yml
    - scripts/**/*
  discard-paths: yes