# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - export RAILS_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/weather-forecast-rails
      - export REACT_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/weather-forecast-react

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Building images - $(date)"

      # 1. Rails image – uses your existing Dockerfile in the root (unchanged)
      - echo "Building Rails image..."
      - docker build -t weather-forecast-rails:$IMAGE_TAG .

      - docker tag weather-forecast-rails:$IMAGE_TAG $RAILS_REPO:$IMAGE_TAG
      - docker tag weather-forecast-rails:$IMAGE_TAG $RAILS_REPO:latest

      # 2. React image – creates a temporary Dockerfile on-the-fly, then builds it
      - echo "Creating temporary Dockerfile for React dev server..."
      - |
        cat > Dockerfile.react <<'EOF'
        FROM node:16-alpine

        WORKDIR /app

        RUN apk add --no-cache netcat-openbsd

        COPY package*.json ./
        RUN npm ci --legacy-peer-deps

        COPY . .

        ENV HOST=0.0.0.0 \
            PORT=3000 \
            CHOKIDAR_USEPOLLING=true \
            HOME=/tmp

        EXPOSE 3000

        CMD sh -c "until nc -z rails 3000; do echo 'Waiting for Rails...'; sleep 3; done && npm run start-docker"
        EOF

      - echo "Building React development server image..."
      - docker build -f Dockerfile.react -t weather-forecast-react:$IMAGE_TAG .

      - docker tag weather-forecast-react:$IMAGE_TAG $REACT_REPO:$IMAGE_TAG
      - docker tag weather-forecast-react:$IMAGE_TAG $REACT_REPO:latest

      # Clean up the temporary file (optional, harmless if skipped)
      - rm -f Dockerfile.react

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push $RAILS_REPO:latest
      - docker push $RAILS_REPO:$IMAGE_TAG
      - docker push $REACT_REPO:latest
      - docker push $REACT_REPO:$IMAGE_TAG

      - printf '[{"name":"rails","imageUri":"%s"},{"name":"react","imageUri":"%s"}]' \
          $RAILS_REPO:$IMAGE_TAG $REACT_REPO:$IMAGE_TAG > imagedefinitions.json

      - echo "Build completed - $(date)"

artifacts:
  files:
    - imagedefinitions.json
    - docker-compose.yml
    - appspec.yml
    - scripts/**/*
  discard-paths: yes